variables:
  MIX_ENV: "test"

tags:
  - elixir

  before_script:
  - mix local.hex --force
  - mix deps.get --only test

test:
  script:
  - mix test

pages:
  script:
  - mix docs --output public
  artifacts:
    paths:
    - public
